# Generated by Django 5.1.1 on 2024-10-24 18:04

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_hd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Helpdesk_list',
        ),
        migrations.RenameField(
            model_name='helpdesk',
            old_name='jmeno',
            new_name='jmeno_zadatele',
        ),
        migrations.RemoveField(
            model_name='helpdesk',
            name='telefon',
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='datum_zalozeni',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='popis_problemu',
            field=models.TextField(default='Není k dispozici'),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='resitel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='termin_splneni',
            field=models.DateField(default=datetime.datetime(2024, 10, 31, 18, 4, 38, 431790, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='helpdesk',
            name='vyjadreni',
            field=models.TextField(blank=True, null=True),
        ),
    ]
