# Generated by Django 5.1.1 on 2024-10-24 18:06

import add_hd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_hd', '0002_delete_helpdesk_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpdesk',
            name='termin_splneni',
            field=models.DateField(default=add_hd.models.get_default_termin_splneni),
        ),
    ]
