# Generated by Django 5.1.1 on 2024-10-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_hd', '0003_alter_helpdesk_termin_splneni'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdesk',
            name='zpracovano',
            field=models.BooleanField(default=False),
        ),
    ]
